Fix-PostScanAction - will display only postScans and not preScan
jenkinsci/checkmarx-plugin pull request #92
Opened 2022-01-10 14:42 UTC by margaritalm

- [ ] Make sure you are opening from a **topic/feature/bugfix branch** (right side) and not your main branch!
- [ ] Ensure that the pull request title represents the desired changelog entry
- [ ] Please describe what you did
- [ ] Link to relevant issues in GitHub or Jira
- [ ] Link to relevant pull requests, esp. upstream and downstream changes
- [ ] Ensure you have provided tests - that demonstrates feature works or fixes the issue

2022-03-03 09:59 UTC, umeshwaghode requested changes

2022-03-03 09:59 UTC, cx-umesh-waghode commented on src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
> +                        if (listBoxModel.isEmpty() && !listBoxModel.contains("")){
Suggestion:  Emtpy entry can be added outside the for loop . That way, if there are no post action command at all, then at least there will be one entry, which will be empty.

2022-03-03 09:59 UTC, cx-umesh-waghode commented on src/main/java/com/checkmarx/jenkins/CxScanBuilder.java
> +                        if (listBoxModel.isEmpty() && !listBoxModel.contains("")){
You can also have first row selected by default:
ListBoxModel.Option op = new ListBoxModel.Option(
                            postAction.getName(), Integer.toString(postAction.getId()))
op.selected = true;
listBoxModel.add(op)

2022-04-07 18:47 UTC, SubhadraSahoo reviewed
@margaritalm , you   can close this PR. In last release of Jenkin security release, we have taken the fix

2022-04-10 06:21 UTC, margaritalm commented
Subject: Re: [jenkinsci/checkmarx-plugin] Fix-PostScanAction - will display only postScans and not preScan (PR #92)

@SubhadraSahoo commented on this pull request.
@margaritalm , you can close this PR. In last release of Jenkin security release, we have taken the fix
—
Reply to this email directly, [view it on GitHub](https://github.com/jenkinsci/checkmarx-plugin/pull/92#pullrequestreview-935535172), or [unsubscribe](https://github.com/notifications/unsubscribe-auth/AK4BDKHHKO7CXS3ASAGFXFDVD4UTJANCNFSM5LT2POUQ).
You are receiving this because you were mentioned. Message ID: <[jenkinsci/checkmarx-plugin/pull/92/review/935535172@github.com](mailto:jenkinsci/checkmarx-plugin/pull/92/review/935535172@github.com)>

2022-04-10 06:21 UTC, closed without merging